import type { Metadata } from "next";
import { Roboto } from "next/font/google";

// 전역 css
import "@/styles/globals.css";
import SideNavigation from "@/components/common/navigation/SideNavigation";

 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ko" className={roboto.className}>
            <body>
                <SideNavigation />
                {children}
            </body>
        </html>
  );
}